// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbowgxakrmxcmcgtinqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNib3dneGFrcm14Y21jZ3RpbnFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDEyMjQsImV4cCI6MjA3NDIxNzIyNH0.t93KoFUJZXBEA_hwon2ULZ8ZWdrHuDA3pjcAEoNWGYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});